// Mocks generated by Mockito 5.4.6 from annotations
// in integra_app/test/unit/http/protocol_http_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i4;
import 'package:integra_app/services/shared_preference_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SharedPreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferenceService extends _i1.Mock
    implements _i2.SharedPreferenceService {
  MockSharedPreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> create({
    required String? accessToken,
    required bool? successStatus,
    required String? tenantDomain,
    required String? subBaseUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #accessToken: accessToken,
            #successStatus: successStatus,
            #tenantDomain: tenantDomain,
            #subBaseUrl: subBaseUrl,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setOnboardingStatus(bool? status) => (super.noSuchMethod(
        Invocation.method(
          #setOnboardingStatus,
          [status],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool getSuccessStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSuccessStatus,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool getOnboardingStatus() => (super.noSuchMethod(
        Invocation.method(
          #getOnboardingStatus,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getNotificationCount() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationCount,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  List<String> getNotificationList() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationList,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.Future<void> setTenantDomain(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #setTenantDomain,
          [domain],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void visualizar() => super.noSuchMethod(
        Invocation.method(
          #visualizar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> limparDados() => (super.noSuchMethod(
        Invocation.method(
          #limparDados,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logoff() => (super.noSuchMethod(
        Invocation.method(
          #logoff,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pageRoute({required _i4.BuildContext? ctx}) =>
      (super.noSuchMethod(
        Invocation.method(
          #pageRoute,
          [],
          {#ctx: ctx},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
