// Mocks generated by Mockito 5.4.6 from annotations
// in integra_app/test/unit/viewmodels/protocol_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i8;
import 'dart:ui' as _i14;

import 'package:flutter/material.dart' as _i12;
import 'package:go_router/go_router.dart' as _i16;
import 'package:integra_app/core/navigation/custom_transitions.dart' as _i17;
import 'package:integra_app/data/models/protocol_appendix_model.dart' as _i3;
import 'package:integra_app/data/models/protocol_attachment_model.dart' as _i4;
import 'package:integra_app/data/models/protocol_model.dart' as _i2;
import 'package:integra_app/data/models/protocol_notification_model.dart'
    as _i5;
import 'package:integra_app/data/models/tenant_model.dart' as _i11;
import 'package:integra_app/data/models/user_model.dart' as _i13;
import 'package:integra_app/presentation/viewmodels/auth/auth_viewmodel.dart'
    as _i10;
import 'package:integra_app/services/http/protocol_http.dart' as _i6;
import 'package:integra_app/services/navigation_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProtocolModel_0 extends _i1.SmartFake implements _i2.ProtocolModel {
  _FakeProtocolModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolAppendixModel_1 extends _i1.SmartFake
    implements _i3.ProtocolAppendixModel {
  _FakeProtocolAppendixModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolAttachmentModel_2 extends _i1.SmartFake
    implements _i4.ProtocolAttachmentModel {
  _FakeProtocolAttachmentModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolNotificationModel_3 extends _i1.SmartFake
    implements _i5.ProtocolNotificationModel {
  _FakeProtocolNotificationModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProtocolHttp].
///
/// See the documentation for Mockito's code generation for more information.
class MockProtocolHttp extends _i1.Mock implements _i6.ProtocolHttp {
  MockProtocolHttp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.ProtocolModel>> getProtocols() => (super.noSuchMethod(
        Invocation.method(
          #getProtocols,
          [],
        ),
        returnValue:
            _i7.Future<List<_i2.ProtocolModel>>.value(<_i2.ProtocolModel>[]),
      ) as _i7.Future<List<_i2.ProtocolModel>>);

  @override
  _i7.Future<_i2.ProtocolModel> createProtocol({
    required String sectorId,
    required String direction,
    required String subject,
    String? documentType,
    String? notes,
    String? originProtocol,
    String? originAgency,
    bool isConfidential = false,
    bool isEmergency = false,
    String? registeredAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProtocol,
          [],
          {
            #sectorId: sectorId,
            #direction: direction,
            #subject: subject,
            #documentType: documentType,
            #notes: notes,
            #originProtocol: originProtocol,
            #originAgency: originAgency,
            #isConfidential: isConfidential,
            #isEmergency: isEmergency,
            #registeredAt: registeredAt,
          },
        ),
        returnValue: _i7.Future<_i2.ProtocolModel>.value(_FakeProtocolModel_0(
          this,
          Invocation.method(
            #createProtocol,
            [],
            {
              #sectorId: sectorId,
              #direction: direction,
              #subject: subject,
              #documentType: documentType,
              #notes: notes,
              #originProtocol: originProtocol,
              #originAgency: originAgency,
              #isConfidential: isConfidential,
              #isEmergency: isEmergency,
              #registeredAt: registeredAt,
            },
          ),
        )),
      ) as _i7.Future<_i2.ProtocolModel>);

  @override
  _i7.Future<_i2.ProtocolModel> cancelProtocol(
    String? id, {
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelProtocol,
          [id],
          {#reason: reason},
        ),
        returnValue: _i7.Future<_i2.ProtocolModel>.value(_FakeProtocolModel_0(
          this,
          Invocation.method(
            #cancelProtocol,
            [id],
            {#reason: reason},
          ),
        )),
      ) as _i7.Future<_i2.ProtocolModel>);

  @override
  _i7.Future<_i2.ProtocolModel> archiveProtocol(
    String? id, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveProtocol,
          [id],
          {#message: message},
        ),
        returnValue: _i7.Future<_i2.ProtocolModel>.value(_FakeProtocolModel_0(
          this,
          Invocation.method(
            #archiveProtocol,
            [id],
            {#message: message},
          ),
        )),
      ) as _i7.Future<_i2.ProtocolModel>);

  @override
  _i7.Future<_i2.ProtocolModel> forwardProtocol(
    String? id, {
    required String? toSectorId,
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forwardProtocol,
          [id],
          {
            #toSectorId: toSectorId,
            #message: message,
          },
        ),
        returnValue: _i7.Future<_i2.ProtocolModel>.value(_FakeProtocolModel_0(
          this,
          Invocation.method(
            #forwardProtocol,
            [id],
            {
              #toSectorId: toSectorId,
              #message: message,
            },
          ),
        )),
      ) as _i7.Future<_i2.ProtocolModel>);

  @override
  _i7.Future<_i2.ProtocolModel> receiveProtocol(
    String? id, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #receiveProtocol,
          [id],
          {#message: message},
        ),
        returnValue: _i7.Future<_i2.ProtocolModel>.value(_FakeProtocolModel_0(
          this,
          Invocation.method(
            #receiveProtocol,
            [id],
            {#message: message},
          ),
        )),
      ) as _i7.Future<_i2.ProtocolModel>);

  @override
  _i7.Future<_i2.ProtocolModel> commentProtocol(
    String? id, {
    required String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #commentProtocol,
          [id],
          {#message: message},
        ),
        returnValue: _i7.Future<_i2.ProtocolModel>.value(_FakeProtocolModel_0(
          this,
          Invocation.method(
            #commentProtocol,
            [id],
            {#message: message},
          ),
        )),
      ) as _i7.Future<_i2.ProtocolModel>);

  @override
  _i7.Future<List<_i3.ProtocolAppendixModel>> getAppendices(
          String? protocolId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppendices,
          [protocolId],
        ),
        returnValue: _i7.Future<List<_i3.ProtocolAppendixModel>>.value(
            <_i3.ProtocolAppendixModel>[]),
      ) as _i7.Future<List<_i3.ProtocolAppendixModel>>);

  @override
  _i7.Future<_i3.ProtocolAppendixModel> createAppendix({
    required String? protocolId,
    required String? title,
    String? documentType,
    String? notes,
    required String? sectorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAppendix,
          [],
          {
            #protocolId: protocolId,
            #title: title,
            #documentType: documentType,
            #notes: notes,
            #sectorId: sectorId,
          },
        ),
        returnValue: _i7.Future<_i3.ProtocolAppendixModel>.value(
            _FakeProtocolAppendixModel_1(
          this,
          Invocation.method(
            #createAppendix,
            [],
            {
              #protocolId: protocolId,
              #title: title,
              #documentType: documentType,
              #notes: notes,
              #sectorId: sectorId,
            },
          ),
        )),
      ) as _i7.Future<_i3.ProtocolAppendixModel>);

  @override
  _i7.Future<_i3.ProtocolAppendixModel> updateAppendix({
    required String? protocolId,
    required String? appendixId,
    String? title,
    String? documentType,
    String? notes,
    String? sectorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppendix,
          [],
          {
            #protocolId: protocolId,
            #appendixId: appendixId,
            #title: title,
            #documentType: documentType,
            #notes: notes,
            #sectorId: sectorId,
          },
        ),
        returnValue: _i7.Future<_i3.ProtocolAppendixModel>.value(
            _FakeProtocolAppendixModel_1(
          this,
          Invocation.method(
            #updateAppendix,
            [],
            {
              #protocolId: protocolId,
              #appendixId: appendixId,
              #title: title,
              #documentType: documentType,
              #notes: notes,
              #sectorId: sectorId,
            },
          ),
        )),
      ) as _i7.Future<_i3.ProtocolAppendixModel>);

  @override
  _i7.Future<void> deleteAppendix(
    String? protocolId,
    String? appendixId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAppendix,
          [
            protocolId,
            appendixId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.ProtocolAttachmentModel>> getAttachments(
    String? protocolId, {
    String? appendixId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttachments,
          [protocolId],
          {#appendixId: appendixId},
        ),
        returnValue: _i7.Future<List<_i4.ProtocolAttachmentModel>>.value(
            <_i4.ProtocolAttachmentModel>[]),
      ) as _i7.Future<List<_i4.ProtocolAttachmentModel>>);

  @override
  _i7.Future<_i4.ProtocolAttachmentModel> uploadAttachment({
    required String? protocolId,
    required _i8.File? file,
    String? category = 'Documento',
    String? appendixId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAttachment,
          [],
          {
            #protocolId: protocolId,
            #file: file,
            #category: category,
            #appendixId: appendixId,
          },
        ),
        returnValue: _i7.Future<_i4.ProtocolAttachmentModel>.value(
            _FakeProtocolAttachmentModel_2(
          this,
          Invocation.method(
            #uploadAttachment,
            [],
            {
              #protocolId: protocolId,
              #file: file,
              #category: category,
              #appendixId: appendixId,
            },
          ),
        )),
      ) as _i7.Future<_i4.ProtocolAttachmentModel>);

  @override
  _i7.Future<void> deleteAttachment(
    String? protocolId,
    String? attachmentId, {
    String? appendixId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAttachment,
          [
            protocolId,
            attachmentId,
          ],
          {#appendixId: appendixId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> downloadAttachment(
    String? protocolId,
    String? attachmentId, {
    String? appendixId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAttachment,
          [
            protocolId,
            attachmentId,
          ],
          {#appendixId: appendixId},
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #downloadAttachment,
            [
              protocolId,
              attachmentId,
            ],
            {#appendixId: appendixId},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<bool> viewAttachment(
    String? protocolId,
    String? attachmentId, {
    String? appendixId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #viewAttachment,
          [
            protocolId,
            attachmentId,
          ],
          {#appendixId: appendixId},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String> getAttachmentViewUrl(
    String? protocolId,
    String? attachmentId, {
    String? appendixId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttachmentViewUrl,
          [
            protocolId,
            attachmentId,
          ],
          {#appendixId: appendixId},
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getAttachmentViewUrl,
            [
              protocolId,
              attachmentId,
            ],
            {#appendixId: appendixId},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateProtocol(
    String? protocolId, {
    required String? documentType,
    required String? subject,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProtocol,
          [protocolId],
          {
            #documentType: documentType,
            #subject: subject,
            #notes: notes,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.Directory?> getDownloadsDirectory() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadsDirectory,
          [],
        ),
        returnValue: _i7.Future<_i8.Directory?>.value(),
      ) as _i7.Future<_i8.Directory?>);

  @override
  _i7.Future<Map<String, dynamic>> getNotifications({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {#page: page},
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i5.ProtocolNotificationModel> markNotificationAsRead(
          String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationAsRead,
          [notificationId],
        ),
        returnValue: _i7.Future<_i5.ProtocolNotificationModel>.value(
            _FakeProtocolNotificationModel_3(
          this,
          Invocation.method(
            #markNotificationAsRead,
            [notificationId],
          ),
        )),
      ) as _i7.Future<_i5.ProtocolNotificationModel>);

  @override
  _i7.Future<void> markMultipleNotificationsAsRead(
          List<String>? notificationIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMultipleNotificationsAsRead,
          [notificationIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i10.AuthViewModel {
  MockAuthViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitializing => (super.noSuchMethod(
        Invocation.getter(#isInitializing),
        returnValue: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get justLoggedIn => (super.noSuchMethod(
        Invocation.getter(#justLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<Map<String, dynamic>> login(
    _i11.Tenant? tenant,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            tenant,
            email,
            password,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<String?> register(
    _i11.Tenant? tenant,
    String? email,
    String? password,
    String? name,
    String? cpf,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            tenant,
            email,
            password,
            name,
            cpf,
            phone,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #loadCurrentUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> offlineLogin(
    _i11.Tenant? requestedTenant, {
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineLogin,
          [requestedTenant],
          {#email: email},
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool hasPermission(String? permission) => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [permission],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #hasRole,
          [role],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearJustLoggedIn() => super.noSuchMethod(
        Invocation.method(
          #clearJustLoggedIn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showLoginSuccessSnackBar(_i12.BuildContext? context) =>
      super.noSuchMethod(
        Invocation.method(
          #showLoginSuccessSnackBar,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showLoginErrorSnackBar(
    _i12.BuildContext? context,
    String? message,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showLoginErrorSnackBar,
          [
            context,
            message,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> saveUserAfterLogin(_i13.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUserAfterLogin,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void startBatchUpdate() => super.noSuchMethod(
        Invocation.method(
          #startBatchUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endBatchUpdate() => super.noSuchMethod(
        Invocation.method(
          #endBatchUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i15.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setRouter(_i16.GoRouter? router) => super.noSuchMethod(
        Invocation.method(
          #setRouter,
          [router],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateTo(
    String? route, {
    Object? extra,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [route],
          {#extra: extra},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushTo(
    String? route, {
    Object? extra,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushTo,
          [route],
          {#extra: extra},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToAndRemoveUntil(
    String? route, {
    Object? extra,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #navigateToAndRemoveUntil,
          [route],
          {#extra: extra},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goBack() => super.noSuchMethod(
        Invocation.method(
          #goBack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool canGoBack() => (super.noSuchMethod(
        Invocation.method(
          #canGoBack,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void navigateToServiceDetail(dynamic service) => super.noSuchMethod(
        Invocation.method(
          #navigateToServiceDetail,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToLogin(dynamic tenant) => super.noSuchMethod(
        Invocation.method(
          #navigateToLogin,
          [tenant],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToHome() => super.noSuchMethod(
        Invocation.method(
          #navigateToHome,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> navigateWithTransition(
    _i12.BuildContext? context,
    _i12.Widget? page, {
    _i17.PageTransitionType? transition = _i17.PageTransitionType.slideRight,
    bool? fullscreenDialog = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [
            context,
            page,
          ],
          {
            #transition: transition,
            #fullscreenDialog: fullscreenDialog,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> navigateToServiceWithHero(
    _i12.BuildContext? context,
    _i12.Widget? servicePage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToServiceWithHero,
          [
            context,
            servicePage,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> navigateToWebView(
    _i12.BuildContext? context,
    _i12.Widget? webViewPage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToWebView,
          [
            context,
            webViewPage,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> navigateToSuccess(
    _i12.BuildContext? context,
    _i12.Widget? successPage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToSuccess,
          [
            context,
            successPage,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> navigateToModal(
    _i12.BuildContext? context,
    _i12.Widget? modalPage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToModal,
          [
            context,
            modalPage,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> replaceWithTransition(
    _i12.BuildContext? context,
    _i12.Widget? page, {
    _i17.PageTransitionType? transition = _i17.PageTransitionType.slideRight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [
            context,
            page,
          ],
          {#transition: transition},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> navigateByContentType(
    _i12.BuildContext? context,
    _i12.Widget? page,
    String? contentType, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateByContentType,
          [
            context,
            page,
            contentType,
          ],
          {#extra: extra},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void navigateToServices(
    _i12.BuildContext? context,
    dynamic category,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #navigateToServices,
          [
            context,
            category,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToServiceDetails(
    dynamic service,
    dynamic category,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #navigateToServiceDetails,
          [
            service,
            category,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToHomeWithBreadcrumbClear(_i12.BuildContext? context) =>
      super.noSuchMethod(
        Invocation.method(
          #navigateToHomeWithBreadcrumbClear,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goBackWithBreadcrumb(_i12.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #goBackWithBreadcrumb,
          [context],
        ),
        returnValueForMissingStub: null,
      );
}
