# .github/workflows/build-all.yml
name: 🔥 Build All (AAB + APK)

on:
  push:
    branches: [production, release]
  workflow_dispatch:

jobs:
  # Primeiro builda AAB
  build-aab:
    uses: ./.github/workflows/build-aab.yml
  
  # Depois builda APK
  build-apk:
    uses: ./.github/workflows/build-apk.yml
    needs: build-aab  # Espera o AAB terminar